services:
  main:
    container_name: icedtea
    build: 
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-user
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - _JAVA_AWT_WM_NONREPARENTING=1
      - AWT_TOOLKIT=MToolkit
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./files:/home/user/files:rw
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    privileged: true
    network_mode: host